language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - travis_wait pip install .
# command to run tests
script:
  - python -m unittest discover tests
  
notifications:
  email: false
